

import type { Metadata } from "next";

import "./globals.css";
import AuthProvider from "@/context/authProvider";
import { Toaster } from "sonner";

import ClientLayout from "./ClientLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    
    <html lang="en">
      <body
        className={` h-full`}
      >
        <AuthProvider>
          <ClientLayout>
        {children}
        </ClientLayout>
        <Toaster/>
        </AuthProvider>
      </body>
    </html>
    
  );
}
