import type { Metadata } from "next";

import "./globals.css";
import AuthProvider from "@/context/authProvider";
import { Toaster } from "sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={` bg-gray-950 h-full`}
      >
        <AuthProvider>
        {children}
        <Toaster/>
        </AuthProvider>
      </body>
    </html>
    
  );
}
